CREATE VIEW `Verano2`
AS SELECT
   `scv`.`id_usuario` AS `IdUsuario`,cast(concat(date_format(`scv`.`fecha_solicitud`,_utf8'%Y%m%d'),_utf8'/',`scv`.`id_usuario`,_utf8'/',`scv`.`id`) as char charset utf8) AS `NúmeroExpediente`,
   `cv`.`titulo` AS `CursoSolicitado`,
   `scv`.`fecha_solicitud` AS `FechaSolicitud`,cast(`scv`.`fecha_aprobado` as date) AS `FechaAprobación`,
   `eccp`.`cursado_fecha_desde` AS `FechaInicio`,
   `eccp`.`cursado_fecha_hasta` AS `FechaFinalización`,
   `d`.`titulo` AS `Duración`,
   `scv`.`estado` AS `Estado`,
   `scv`.`estado_pago` AS `EstadoPago`,
   `scv`.`observaciones_mod_pago` AS `ObsModPago`,
   `scv`.`tipo_pago` AS `TipoPago`,
   `scv`.`importe_total` AS `Importe`,(case when (`scv`.`tc_importe_pagado` > 0) then `scv`.`tc_importe_pagado` else NULL end) AS `TarjetaImportePagado`,
   `scv`.`referencia` AS `referencia`,
   `scv`.`tc_fecha_pagado` AS `TarjetaFechaPagado`,(case when `av`.`ID` then `av`.`nombre` else `a`.`nombre` end) AS `Nombre`,(case when `av`.`ID` then `av`.`apellidos` else `a`.`apellidos` end) AS `Apellido`,(case when `av`.`ID` then `av`.`apellidos2` else `a`.`apellidos2` end) AS `SegundoApellido`,(case when `av`.`ID` then `av`.`fecha_nacimiento` else `a`.`fecha_nacimiento` end) AS `FechaNacimiento`,(case when (`scv`.`id_colegio_origen` = -(1)) then `scv`.`otro_colegio_origen` else NULL end) AS `OtroColegioOrigen`,cast(if((locate(_utf8'Educa',`nf`.`titulo`) > 0),concat(left(`nf`.`titulo`,1),_utf8'º',right(`nf`.`titulo`,(length(`nf`.`titulo`) - 14))),if((locate(_utf8'Nursery (4 años)',`nf`.`titulo`) > 0),_utf8'2º Infantil',`nf`.`titulo`)) as char charset utf8) AS `CursoActual`,
   `scv`.`grupo_origen` AS `Grupo`,
   `scv`.`horas_ingles_colegio` AS `HorasInglésColegio`,
   `scv`.`requiere_atencion_especial` AS `RequiereAtenciónEspecial`,
   `tv`.`nombre` AS `NombreTutor`,
   `tv`.`apellidos` AS `ApellidoTutor`,
   `tv`.`apellidos2` AS `SegundoApellidoTutor`,
   `tv`.`direccion` AS `DirecciónTutor`,
   `tv`.`codigo_postal` AS `CódigoPostalTutor`,
   `p`.`provincia` AS `ProvinciaTutor`,
   `tv`.`telefono_casa` AS `TeléfonoTutor`,
   `tv`.`telefono_movil` AS `MóvilTutor`,
   `tv`.`email` AS `EmailTutor`,
   `tv2`.`nombre` AS `NombreTutora`,
   `tv2`.`apellidos` AS `ApellidoTutora`,
   `tv2`.`apellidos2` AS `SegundoApellidoTutora`,
   `tv2`.`direccion` AS `DirecciónTutora`,
   `tv2`.`codigo_postal` AS `CódigoPostalTutora`,
   `p2`.`provincia` AS `ProvinciaTutora`,
   `tv2`.`telefono_casa` AS `TeléfonoTutora`,
   `tv2`.`telefono_movil` AS `MóvilTutora`,
   `tv2`.`email` AS `EmailTutora`,
   FROM ((((((((((((`cv_solicitud_curso_verano` `scv` left join `cv_edicion_curso_centro_periodos` `eccp` on((`scv`.`id_cv_edicion_curso_centro_periodos` = `eccp`.`id`))) left join `cv_edicion_curso_centro` `ecc` on((`eccp`.`id_cv_edicion_curso_centro` = `ecc`.`id`))) left join `centros` `c` on((`scv`.`id_colegio_solicitado` = `c`.`id`))) left join `cvsys_cursos_verano` `cv` on((`scv`.`id_curso_solicitado` = `cv`.`id`))) left join `alumnos_verano` `av` on((`scv`.`id_alumno` = `av`.`ID`))) left join `alumnos` `a` on((`scv`.`id_alumno` = `a`.`ID`))) left join `tutores_verano` `tv` on((`scv`.`id_tutor` = `tv`.`ID`))) left join `provincias` `p` on((`tv`.`id_provincia` = `p`.`id`))) left join `tutores_verano` `tv2` on((`scv`.`id_tutora` = `tv2`.`ID`))) left join `provincias` `p2` on((`tv2`.`id_provincia` = `p2`.`id`))) left join `cvsys_duraciones` `d` on((`eccp`.`id_cvsys_duraciones` = `d`.`id`))) left join `niveles_formacion` `nf` on((`scv`.`id_curso_origen` = `nf`.`id`))) where (((`scv`.`estado` = _utf8'aprobada') or (`scv`.`estado` = _utf8'pendiente')) and (year(`scv`.`fecha_solicitud`) = 2014) and (`scv`.`id_colegio_solicitado` = 1));